### ISSUE TITLE
Passing TOR Socks5 proxy check

### ISSUE THREAD

**Issue by fuuddanni** [decoxviii/karma#1]
I don´t want to run the sick tor on my machine: Am i able to use your tool by changing functions in core.py? `
    """Docstring for pwndb. """

    def __init__(self, args):
        self.domain = 'http://pwndb2am4tzkvold.onion.**to**/'
        self.args = args
        self.data = {
            'luseropr'  : 0,
            'domainopr' : 0,
            'submitform': 'em'
        }

        proxy = self.args['--proxy']
        if '//' in proxy:
            proxy = proxy.split('//')[1]

        self.session = requests.session()
        self.session.proxies = {
            'http' : 'socks5h://%s' % proxy,
            'https': 'socks5h://%s' % proxy
        }` 

Piping through my local proxy doesn´t work, guessing the proxy tries to reach the Darkweb, right?

**Comment by decoxviii** [comment]
Hi @fuuddanni 

> I don´t want to run the sick tor on my machine...

It's necessary to run Tor on your machine, otherwise it will not be able to connect to the server: `http://pwndb2am4tzkvold.onion`
