### ISSUE TITLE
the site: http://pwndb2am4tzkvold.onion/ is down, try again later 

### ISSUE THREAD

**Issue by SirmaXX** [decoxviii/karma#12]
this website isnt working :/ ,how can ı solve this problem (ı had installed tor )

**Comment by decoxviii** [comment]
Hi @SirmaXX,

The site is hosted on the _deep web_, it is normal for this to happen. But I just tried the tool and the service is active right now. Please try again!

**Comment by Villelmo** [comment]
@decoxviii Why is normal the issue?. The service is active right now but the tool don't give me results.

**Comment by decoxviii** [comment]
HI @Villelmo,

The service is down, if you try to access the site you get the following error:
```
Warning: mysqli::__construct(): (HY000/2002): No such file or directory in /var/www/html/index.php on line 12
Connection failed: No such file or directory
```
