### ISSUE TITLE
API/Web not working

### ISSUE THREAD

**Issue by Villelmo** [decoxviii/karma#14]
The website http://pwndb2am4tzkvold.onion/ show the following issue:

```
Warning: mysqli::__construct(): (HY000/2002): No such file or directory in /var/www/html/index.php on line 12
Connection failed: No such file or directory

```
I'm trying API/Web every the week but yesterday begin this problem from 12:00am until now.

**Comment by decoxviii** [comment]
It's normal for these services to fall temporarily. I will close this problem when the service is activated again.

**Comment by Villelmo** [comment]
3 days down the website. :(

**Comment by decoxviii** [comment]
> appypollyloggies (2019.04.15)
> Sorry for the downtime

I just did a test, it's working again!
