### ISSUE TITLE
Failed to establish a new connection: [Errno 61] Connection refused

### ISSUE THREAD

**Issue by smetal1** [decoxviii/karma#15]
**Error:**
```
SOCKSHTTPConnectionPool(host='pwndb2am4tzkvold.onion', port=80): Max retries exceeded with
url: / (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSConnection object at
0x10871d410>: Failed to establish a new connection: [Errno 61] Connection refused'))
```

**Comment by decoxviii** [comment]
Hi @smetal1,

Can you show me the result of the following command?
```
cd karma
pip3 freeze | grep -i -f requirements.txt
```

**Comment by decoxviii** [comment]
@smetal1 does not answer, I will close this issue

**Comment by mosal68** [comment]
hi
im having this problem.. anyway you can fix it.
i typed karma target 'johndoe@unknown.com' -o test4
(with my email)

**Comment by decoxviii** [comment]
Hi @mosal68,

Can you please show me the result of the following command?
```
cd karma
pip3 freeze | grep -i -f requirements.txt
```

**Comment by mosal68** [comment]
its working now thanks

**Comment by decoxviii** [comment]
Please could you specify What is causing this problem? o How did you solve the problem?

**Comment by mosal68** [comment]
it happens everytime you open karma
with/without tor opend

but when you use the sudo service tor start it starts working

**Comment by decoxviii** [comment]
Thanks for replying, I will close this issue.
