### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character '\xe0' in position 46222: ordinal not in range(128)

### ISSUE THREAD

**Issue by polidorino** [decoxviii/karma#16]
All search by domain works, but sometimes give this error:

```
Traceback (most recent call last):
  [...]
  File "/usr/local/lib/python3.6/site-packages/karma-1.2.1-py3.6.egg/EGG-INFO/scripts/karma", line 52, in print_result_table
UnicodeEncodeError: 'ascii' codec can't encode character '\xe0' in position 46222: ordinal not in range(128)
```

May some character in mail address cause fault?

**Comment by decoxviii** [comment]
Hi @polidorino,

Can you provide the following information?

**To Reproduce**
Steps to reproduce the behavior:
1. Install with the command: '...'
2. Run this: '....'
3. See error

**Comment by polidorino** [comment]
Hi Sergio,
same error....trying with Python 3.5, installing and running as root...the
same

Here last output:

root@osint:/usr/bin# cd /root/
root@osint:~# ls
root@osint:~# git clone https://github.com/decoxviii/karma.git ; cd karma
Cloning into 'karma'...
remote: Enumerating objects: 54, done.
remote: Counting objects: 100% (54/54), done.
remote: Compressing objects: 100% (33/33), done.
remote: Total 102 (delta 28), reused 32 (delta 18), pack-reused 48
Receiving objects: 100% (102/102), 22.25 KiB | 0 bytes/s, done.
Resolving deltas: 100% (47/47), done.
Checking connectivity... done.
root@osint:~/karma# pip3 install -r requirements.txt
Requirement already satisfied (use --upgrade to upgrade): pysocks in
/usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): texttable in
/usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): docopt in
/usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): requests in
/usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade):
certifi>=2017.4.17 in /usr/local/lib/python3.5/dist-packages (from
requests->-r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): idna<2.9,>=2.5 in
/usr/local/lib/python3.5/dist-packages (from requests->-r requirements.txt
(line 4))
Requirement already satisfied (use --upgrade to upgrade):
chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.5/dist-packages (from
requests->-r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade):
urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in
/usr/local/lib/python3.5/dist-packages (from requests->-r requirements.txt
(line 4))
You are using pip version 8.1.1, however version 19.2.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
root@osint:~/karma# python3 setup.py build
running build
running build_py
creating build
creating build/lib
creating build/lib/karma
copying karma/banner.py -> build/lib/karma
copying karma/__init__.py -> build/lib/karma
copying karma/version.py -> build/lib/karma
copying karma/formatter.py -> build/lib/karma
copying karma/core.py -> build/lib/karma
running build_scripts
creating build/scripts-3.5
copying and adjusting bin/karma -> build/scripts-3.5
changing mode of build/scripts-3.5/karma from 644 to 755
root@osint:~/karma# python3 setup.py install
running install
Checking .pth file support in /usr/local/lib/python3.5/dist-packages/
/usr/bin/python3 -E -c pass
TEST PASSED: /usr/local/lib/python3.5/dist-packages/ appears to support
.pth files
running bdist_egg
running egg_info
creating karma.egg-info
writing top-level names to karma.egg-info/top_level.txt
writing karma.egg-info/PKG-INFO
writing requirements to karma.egg-info/requires.txt
writing dependency_links to karma.egg-info/dependency_links.txt
writing manifest file 'karma.egg-info/SOURCES.txt'
reading manifest file 'karma.egg-info/SOURCES.txt'
writing manifest file 'karma.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/karma
copying build/lib/karma/banner.py -> build/bdist.linux-x86_64/egg/karma
copying build/lib/karma/__init__.py -> build/bdist.linux-x86_64/egg/karma
copying build/lib/karma/version.py -> build/bdist.linux-x86_64/egg/karma
copying build/lib/karma/formatter.py -> build/bdist.linux-x86_64/egg/karma
copying build/lib/karma/core.py -> build/bdist.linux-x86_64/egg/karma
byte-compiling build/bdist.linux-x86_64/egg/karma/banner.py to
banner.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/karma/__init__.py to
__init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/karma/version.py to
version.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/karma/formatter.py to
formatter.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/karma/core.py to
core.cpython-35.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
installing scripts to build/bdist.linux-x86_64/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
creating build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.5/karma ->
build/bdist.linux-x86_64/egg/EGG-INFO/scripts
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/karma to 755
copying karma.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying karma.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying karma.egg-info/dependency_links.txt ->
build/bdist.linux-x86_64/egg/EGG-INFO
copying karma.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying karma.egg-info/top_level.txt ->
build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/karma-1.2.1-py3.5.egg' and adding
'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing karma-1.2.1-py3.5.egg
Copying karma-1.2.1-py3.5.egg to /usr/local/lib/python3.5/dist-packages
Adding karma 1.2.1 to easy-install.pth file
Installing karma script to /usr/local/bin

Installed /usr/local/lib/python3.5/dist-packages/karma-1.2.1-py3.5.egg
Processing dependencies for karma==1.2.1
Searching for requests==2.22.0
Best match: requests 2.22.0
Adding requests 2.22.0 to easy-install.pth file

Using /usr/local/lib/python3.5/dist-packages
Searching for docopt==0.6.2
Best match: docopt 0.6.2
docopt 0.6.2 is already the active version in easy-install.pth

Using /usr/local/lib/python3.5/dist-packages
Searching for texttable==1.6.2
Best match: texttable 1.6.2
texttable 1.6.2 is already the active version in easy-install.pth

Using /usr/local/lib/python3.5/dist-packages
Searching for PySocks==1.7.1
Best match: PySocks 1.7.1
PySocks 1.7.1 is already the active version in easy-install.pth

Using /usr/local/lib/python3.5/dist-packages
Searching for urllib3==1.25.6
Best match: urllib3 1.25.6
urllib3 1.25.6 is already the active version in easy-install.pth

Using /usr/local/lib/python3.5/dist-packages
Searching for certifi==2019.9.11
Best match: certifi 2019.9.11
certifi 2019.9.11 is already the active version in easy-install.pth

Using /usr/local/lib/python3.5/dist-packages
Searching for chardet==3.0.4
Best match: chardet 3.0.4
chardet 3.0.4 is already the active version in easy-install.pth
Installing chardetect script to /usr/local/bin

Using /usr/local/lib/python3.5/dist-packages
Searching for idna==2.8
Best match: idna 2.8
idna 2.8 is already the active version in easy-install.pth

Using /usr/local/lib/python3.5/dist-packages
Finished processing dependencies for karma==1.2.1
root@osint:~/karma#

#TEST1
root@osint:~/karma# karma search 'XXXXXX.com' --domain


        K C B E N T S Z 0
        8 W K A R M A Z S
        C D M U Z J E Y 5

        decoxviii
        1.2.1

[+] starting search
[+] 1/1 request domain:  XXXXXX.com
[+] analyzing results:
Traceback (most recent call last):
  File "/usr/local/bin/karma", line 4, in <module>
    __import__('pkg_resources').run_script('karma==1.2.1', 'karma')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line
719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line
1511, in run_script
    exec(script_code, namespace, namespace)
  File
"/usr/local/lib/python3.5/dist-packages/karma-1.2.1-py3.5.egg/EGG-INFO/scripts/karma",
line 103, in <module>
  File
"/usr/local/lib/python3.5/dist-packages/karma-1.2.1-py3.5.egg/EGG-INFO/scripts/karma",
line 95, in main
  File
"/usr/local/lib/python3.5/dist-packages/karma-1.2.1-py3.5.egg/EGG-INFO/scripts/karma",
line 52, in print_result_table
UnicodeEncodeError: 'ascii' codec can't encode character '\xe0' in position
2401: ordinal not in range(128)


#TEST2 (Other domain)

root@osint:~/karma# karma search ' XXXXYY.com ' --domain


        F W Z H L K E D B
        D G K A R M A L C
        N M 2 B L W H O 8

        decoxviii
        1.2.1

[+] starting search
[+] 1/1 request domain: XXXXYY.com
[+] analyzing results:
+------------------------------+------------------------------------+
|            Email             |              Password              |

................
...............
...............

[+] 48 results found in 3.71s


Everything is ok.


Best regards,
Alessandro

Il giorno mar 1 ott 2019 alle ore 20:09 Sergio SA <notifications@github.com>
ha scritto:

**Comment by decoxviii** [comment]
I tried to replicate this error but I couldn't.  Could you modify the following lines, to see if the error is corrected?

File: `bin/karma`
```python
for key in result.keys():
        email = result[key]["email"]
        passw = str(result[key]["passw"])
        row = (email, passw)
        table.add_row(row)
```

```python
for key in result.keys():
        email = result[key]["email"].encode("utf-8")
        passw = result[key]["passw"].encode("utf-8")
        row = (email, passw)
        table.add_row(row)
```

**Comment by polidorino** [comment]
HI Sergio,
here the modified code:


...............................................
def print_result_table(result, start_time):

    table = Texttable()
    table.header(["Email", "Password"])
    table.set_cols_dtype(["t", "t"])
    table.set_deco(Texttable.BORDER | Texttable.HEADER | Texttable.VLINES)

    for key in result.keys():
        *email = result[key]["email"].encode("utf-8")*
        *passw = result[key]["passw"].encode("utf-8")*
        row = (email, passw)
        table.add_row(row)

    *print(table.draw().encode("utf-8"))*
    logger.info(
        "{} results found in {:.2f}s".format(
            len(result.keys()), time.time() - start_time
        )
    )



.........

With your modified code but without encoding in print finally dont' crash
but don't display nothing on screen (no table, write to output if selected).
WIth encode("utf-8") table is not aligned but show results and print
correct to json file.

If we can find how align table on screen it's perfect, but it's perfect
also,too.

Thank you so much,
Alessandro

Il giorno mer 2 ott 2019 alle ore 20:31 Sergio SA <notifications@github.com>
ha scritto:

**Comment by decoxviii** [comment]
I have tried to replicate the error but I have not succeeded, could I specify which domain returns this error? That way I could work on this and correct it. You can send it to me by email if you don't want to make it public.

email: `decoxviii(at)gmail[.]com`

**Comment by decoxviii** [comment]
@polidorino does not answer, I will close this issue

**Comment by polidorino** [comment]
HI Segio,
I'don't reply because I was doing multiple tests on multiple installations.
In my opinion, close a report because after one or two days you have no
answer is not correct, maybe people are still at work or may be something
other, but the choice is yours.

Finally,
the problem was on the server that I use for development, probably due to a
multiple Python 3.X installations.
On other 3 virtual machines  (Kali and 2 Ubuntu 18.04) it works perfectly.

Thank you so much,
Alessandro





Il giorno sab 5 ott 2019 alle ore 20:06 Sergio SA <notifications@github.com>
ha scritto:

**Comment by decoxviii** [comment]
Hi @polidorino,

Thanks for replying, I apologize for closing this issue quickly. I assumed that the problem had already been solved. From now on I will not close any until it is confirmed that the problem has been solved.
