### ISSUE TITLE
SOCKSHTTPConnectionPool error

### ISSUE THREAD

**Issue by DougP19** [decoxviii/karma#2]
Getting this error after attempting any type of search on Kali Rolling 2019.1 with all requirements installed and updated/upgraded:

> Starting 

	E Q Z V T R Z N W
	2 U K A R M A R J
	Z B Y M H 3 T Y S

	decoxviii
	15.03.19

> Searching

Error: SOCKSHTTPConnectionPool(host='pwndb2am4tzkvold.onion', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSConnection object at 0x7fc565cb7ac8>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by decoxviii** [comment]
Hi @DougP19 

Check that the Tor service is running. Run:
`sudo service tor restart`

and try again.
