### ISSUE TITLE
Error: SOCKSHTTPConnectionPool

### ISSUE THREAD

**Issue by sundharc** [decoxviii/karma#3]
> Starting 

	S W E F G J N O T
	0 L K A R M A K B
	T Y E S N 6 M V 1

	decoxviii
	15.03.19

> Searching
Error: SOCKSHTTPConnectionPool(host='pwndb2am4tzkvold.onion', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSConnection object at 0x7fd3bded7c50>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by decoxviii** [comment]
Hi @sundharc 

Check this Issue: [SOCKSHTTPConnectionPool error #2](https://github.com/decoxviii/karma/issues/2)
