### ISSUE TITLE
Error: Unable to determine SOCKS version from socks5h://127.0.0.1:9050

### ISSUE THREAD

**Issue by ramocha** [decoxviii/karma#4]
Hi,

i just install the Karma and i have a problem when i try to use... the error was "Error: Unable to determine SOCKS version from socks5h://127.0.0.1:9050"

![image](https://user-images.githubusercontent.com/32308463/54638062-e32de200-4a68-11e9-9094-aabae2d2440b.png)

i search in the code and the problem is here

![image](https://user-images.githubusercontent.com/32308463/54638115-06f12800-4a69-11e9-8896-90265d55fb8f.png)

when i delete the h in the code it's work fine

![image](https://user-images.githubusercontent.com/32308463/54638189-36a03000-4a69-11e9-87cf-b8188bc6fffa.png)

i hope this help someone

**Comment by decoxviii** [comment]
Hi @ramocha 

Have you deleted the lines of code?
```python
self.session.proxies = {
            'http' : 'socks5h://%s' % proxy,
            'https': 'socks5h://%s' % proxy
        }
```
or just made a modification.

**Comment by ramocha** [comment]
Hi @decoxviii

I just delete only the h of socks5h in this 2 líneas.

**Comment by decoxviii** [comment]
On my computer when modifying the code lines:
```python
self.session.proxies = {
    #'http' : 'socks5h://%s' % proxy,
    'http' : 'socks5://%s' % proxy,
    #'https': 'socks5h://%s' % proxy
    'https': 'socks5://%s' % proxy
}
```
I have this error: _SOCKSHTTPConnectionPool..._

Possibly we have different versions of the libraries `requests` and `pysocks`. In my case I have installed:
+ `requests (2.18.4)`
+ `PySocks (1.6.8)`

**Comment by swatts07** [comment]
Sir how can i open this nano window what is the command and i have another question my friend has tested this tool and he told me that it dont work it allways give him 0 result found

**Comment by decoxviii** [comment]
Hi @swatts07 

> how can i open this nano window what is the command

1. Open a terminal and run: `nano karma/core.py`

_Before using this tool I advise you to take a course on the intruding of the terminal in Linux._

---

> my friend has tested this tool and he told me that it dont work it always give him 0 result found

2. When executing: `python3 bin/karma.py search hotmail.com --domain,` you also get 0 results? If your answer is affirmative, there will be a new issue to work on this

**Comment by swatts07** [comment]
Hello sir i have question i know it is realy strange but it is okey . Can we be friends ? Lol

**Comment by swatts07** [comment]
And please sir find another seloution this seloution got me another problem if u have facebook or something to message u on tell i'll send pics
