### ISSUE TITLE
Error: SOCKSHTTPConnectionPool

### ISSUE THREAD

**Issue by amirasyraf** [decoxviii/karma#6]
Hi,

Before you reference issues which you have closed before waiting for their reply on whether or not it works, read first.

Tor service is started and running. I have restarted the service and it still gave the following error:

> Error: SOCKSHTTPConnectionPool(host='pwndb2am4tzkvold.onion', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSConnection object at 0x7fa6a4806198>: Failed to establish a new connection: 0x06: TTL expired',))

Ubuntu 18.04

**Comment by shelu16** [comment]
pwndb2am4tzkvold domain is down so tool is not working

**Comment by decoxviii** [comment]
The site: **pwndb2am4tzkvold** is enabled again.

**Comment by amirasyraf** [comment]
Still not working. I tried on my local and remote machines.

`Error: SOCKSHTTPConnectionPool(host='pwndb2am4tzkvold.onion', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSConnection object at 0x7fc70837efd0>: Failed to establish a new connection: [Errno 111] Connection refused',))`

**Comment by decoxviii** [comment]
I get the same error when I stop the `tor` service.

**Comment by shelu16** [comment]
Hi
 This is working fine . With service tor start

**Comment by amirasyraf** [comment]
Somehow it works now. Thank you.
