### ISSUE TITLE
Error: Not supported proxy scheme socks5h

### ISSUE THREAD

**Issue by nicolasheise** [decoxviii/karma#7]
Hi,
I have a little problem, when I run the command "python3 bin/karma search '12345678' --password" the cli give me the message "Error: Not supported proxy scheme socks5h"

Somebody know how to solve this?

Thanks
pd: sorry for my bad english

**Comment by decoxviii** [comment]
Hi @nicolasheise,

Try installing the requirements (see `requirements.txt`) again. execute:

```bash
sudo -H pip3 install -r requirements.txt --upgrade
```
or you can also try installing the tool using `pip3`:
```bash
sudo -H pip3 install git+https://github.com/decoxviii/karma.git
karma --help
karma search '123456789' --password
```

**Comment by chasingdreamm** [comment]
decoxviii 

I have sended you on email,when you have time please respond me.

THANKS

**Comment by nicolasheise** [comment]
I'm sorry but actually I don't have much time.

Well, just like you said, I had to reinstall the requirements and finally
works perfectly

Thanks for your help

**Comment by nicolasheise** [comment]
I'm sorry but actually I don't have much time.

Well, just like you said, I had to reinstall the requirements and finally works perfectly

Thanks for your help
