### ISSUE TITLE
API/Web not working (down maybe?)

### ISSUE THREAD

**Issue by anir0y** [decoxviii/karma#8]
the API/TOR endpoint seems down for some reason. 

URL: http://pwndb2am4tzkvold.onion/

**Comment by decoxviii** [comment]
Yes, this had happened before. Possibly within a short time it will be active again

**Comment by decoxviii** [comment]
The site is enabled again!

**Comment by Villelmo** [comment]
3 days API/Web not working. @decoxviii. What's the problem before?. Now the problem is the following:

```
Warning: mysqli::__construct(): (HY000/2002): No such file or directory in /var/www/html/index.php on line 12
Connection failed: No such file or directory
```
